var annotated_dup =
[
    [ "mUPnP", "namespacemUPnP.html", [
      [ "Action", "classmUPnP_1_1Action.html", "classmUPnP_1_1Action" ],
      [ "ActionData", "classmUPnP_1_1ActionData.html", "classmUPnP_1_1ActionData" ],
      [ "ActionList", "classmUPnP_1_1ActionList.html", "classmUPnP_1_1ActionList" ],
      [ "ActionListener", "classmUPnP_1_1ActionListener.html", "classmUPnP_1_1ActionListener" ],
      [ "ActionRequest", "classmUPnP_1_1ActionRequest.html", "classmUPnP_1_1ActionRequest" ],
      [ "ActionResponse", "classmUPnP_1_1ActionResponse.html", "classmUPnP_1_1ActionResponse" ],
      [ "Advertiser", "classmUPnP_1_1Advertiser.html", "classmUPnP_1_1Advertiser" ],
      [ "AllowedValue", "classmUPnP_1_1AllowedValue.html", "classmUPnP_1_1AllowedValue" ],
      [ "AllowedValueList", "classmUPnP_1_1AllowedValueList.html", "classmUPnP_1_1AllowedValueList" ],
      [ "AllowedValueRange", "classmUPnP_1_1AllowedValueRange.html", "classmUPnP_1_1AllowedValueRange" ],
      [ "Argument", "classmUPnP_1_1Argument.html", "classmUPnP_1_1Argument" ],
      [ "ArgumentData", "classmUPnP_1_1ArgumentData.html", "classmUPnP_1_1ArgumentData" ],
      [ "ArgumentList", "classmUPnP_1_1ArgumentList.html", "classmUPnP_1_1ArgumentList" ],
      [ "ControlPoint", "classmUPnP_1_1ControlPoint.html", "classmUPnP_1_1ControlPoint" ],
      [ "ControlRequest", "classmUPnP_1_1ControlRequest.html", "classmUPnP_1_1ControlRequest" ],
      [ "ControlResponse", "classmUPnP_1_1ControlResponse.html", "classmUPnP_1_1ControlResponse" ],
      [ "Device", "classmUPnP_1_1Device.html", "classmUPnP_1_1Device" ],
      [ "DeviceChangeListener", "classmUPnP_1_1DeviceChangeListener.html", "classmUPnP_1_1DeviceChangeListener" ],
      [ "DeviceData", "classmUPnP_1_1DeviceData.html", "classmUPnP_1_1DeviceData" ],
      [ "DeviceList", "classmUPnP_1_1DeviceList.html", "classmUPnP_1_1DeviceList" ],
      [ "Disposer", "classmUPnP_1_1Disposer.html", "classmUPnP_1_1Disposer" ],
      [ "EventListener", "classmUPnP_1_1EventListener.html", "classmUPnP_1_1EventListener" ],
      [ "HTTPMUSocket", "classmUPnP_1_1HTTPMUSocket.html", "classmUPnP_1_1HTTPMUSocket" ],
      [ "HTTPUSocket", "classmUPnP_1_1HTTPUSocket.html", "classmUPnP_1_1HTTPUSocket" ],
      [ "Icon", "classmUPnP_1_1Icon.html", "classmUPnP_1_1Icon" ],
      [ "IconList", "classmUPnP_1_1IconList.html", "classmUPnP_1_1IconList" ],
      [ "InvalidDescriptionException", "classmUPnP_1_1InvalidDescriptionException.html", "classmUPnP_1_1InvalidDescriptionException" ],
      [ "NotifyListener", "classmUPnP_1_1NotifyListener.html", "classmUPnP_1_1NotifyListener" ],
      [ "NotifyRequest", "classmUPnP_1_1NotifyRequest.html", "classmUPnP_1_1NotifyRequest" ],
      [ "Property", "classmUPnP_1_1Property.html", "classmUPnP_1_1Property" ],
      [ "PropertyList", "classmUPnP_1_1PropertyList.html", "classmUPnP_1_1PropertyList" ],
      [ "QueryListener", "classmUPnP_1_1QueryListener.html", "classmUPnP_1_1QueryListener" ],
      [ "QueryRequest", "classmUPnP_1_1QueryRequest.html", "classmUPnP_1_1QueryRequest" ],
      [ "QueryResponse", "classmUPnP_1_1QueryResponse.html", "classmUPnP_1_1QueryResponse" ],
      [ "RenewSubscriber", "classmUPnP_1_1RenewSubscriber.html", "classmUPnP_1_1RenewSubscriber" ],
      [ "SearchListener", "classmUPnP_1_1SearchListener.html", "classmUPnP_1_1SearchListener" ],
      [ "SearchResponseListener", "classmUPnP_1_1SearchResponseListener.html", "classmUPnP_1_1SearchResponseListener" ],
      [ "Service", "classmUPnP_1_1Service.html", "classmUPnP_1_1Service" ],
      [ "ServiceData", "classmUPnP_1_1ServiceData.html", "classmUPnP_1_1ServiceData" ],
      [ "ServiceList", "classmUPnP_1_1ServiceList.html", "classmUPnP_1_1ServiceList" ],
      [ "ServiceStateTable", "classmUPnP_1_1ServiceStateTable.html", "classmUPnP_1_1ServiceStateTable" ],
      [ "SharedVector", "classmUPnP_1_1SharedVector.html", "classmUPnP_1_1SharedVector" ],
      [ "SSDPNotifyRequest", "classmUPnP_1_1SSDPNotifyRequest.html", "classmUPnP_1_1SSDPNotifyRequest" ],
      [ "SSDPNotifySocket", "classmUPnP_1_1SSDPNotifySocket.html", "classmUPnP_1_1SSDPNotifySocket" ],
      [ "SSDPNotifySocketList", "classmUPnP_1_1SSDPNotifySocketList.html", "classmUPnP_1_1SSDPNotifySocketList" ],
      [ "SSDPPacket", "classmUPnP_1_1SSDPPacket.html", "classmUPnP_1_1SSDPPacket" ],
      [ "SSDPRequest", "classmUPnP_1_1SSDPRequest.html", "classmUPnP_1_1SSDPRequest" ],
      [ "SSDPResponse", "classmUPnP_1_1SSDPResponse.html", "classmUPnP_1_1SSDPResponse" ],
      [ "SSDPSearchRequest", "classmUPnP_1_1SSDPSearchRequest.html", "classmUPnP_1_1SSDPSearchRequest" ],
      [ "SSDPSearchResponse", "classmUPnP_1_1SSDPSearchResponse.html", "classmUPnP_1_1SSDPSearchResponse" ],
      [ "SSDPSearchResponseSocket", "classmUPnP_1_1SSDPSearchResponseSocket.html", "classmUPnP_1_1SSDPSearchResponseSocket" ],
      [ "SSDPSearchResponseSocketList", "classmUPnP_1_1SSDPSearchResponseSocketList.html", "classmUPnP_1_1SSDPSearchResponseSocketList" ],
      [ "SSDPSearchSocket", "classmUPnP_1_1SSDPSearchSocket.html", "classmUPnP_1_1SSDPSearchSocket" ],
      [ "SSDPSearchSocketList", "classmUPnP_1_1SSDPSearchSocketList.html", "classmUPnP_1_1SSDPSearchSocketList" ],
      [ "StateVariable", "classmUPnP_1_1StateVariable.html", "classmUPnP_1_1StateVariable" ],
      [ "StateVariableData", "classmUPnP_1_1StateVariableData.html", "classmUPnP_1_1StateVariableData" ],
      [ "Subscriber", "classmUPnP_1_1Subscriber.html", "classmUPnP_1_1Subscriber" ],
      [ "SubscriberList", "classmUPnP_1_1SubscriberList.html", "classmUPnP_1_1SubscriberList" ],
      [ "SubscriptionRequest", "classmUPnP_1_1SubscriptionRequest.html", "classmUPnP_1_1SubscriptionRequest" ],
      [ "SubscriptionResponse", "classmUPnP_1_1SubscriptionResponse.html", "classmUPnP_1_1SubscriptionResponse" ],
      [ "UPnPStatus", "classmUPnP_1_1UPnPStatus.html", "classmUPnP_1_1UPnPStatus" ],
      [ "Vector", "classmUPnP_1_1Vector.html", "classmUPnP_1_1Vector" ],
      [ "WeakVector", "classmUPnP_1_1WeakVector.html", "classmUPnP_1_1WeakVector" ]
    ] ],
    [ "uSOAP", "namespaceuSOAP.html", [
      [ "SOAPRequest", "classuSOAP_1_1SOAPRequest.html", "classuSOAP_1_1SOAPRequest" ],
      [ "SOAPResponse", "classuSOAP_1_1SOAPResponse.html", "classuSOAP_1_1SOAPResponse" ]
    ] ],
    [ "uXML", "namespaceuXML.html", [
      [ "Attribute", "classuXML_1_1Attribute.html", "classuXML_1_1Attribute" ],
      [ "AttributeList", "classuXML_1_1AttributeList.html", "classuXML_1_1AttributeList" ],
      [ "Node", "classuXML_1_1Node.html", "classuXML_1_1Node" ],
      [ "NodeData", "classuXML_1_1NodeData.html", "classuXML_1_1NodeData" ],
      [ "NodeList", "classuXML_1_1NodeList.html", "classuXML_1_1NodeList" ],
      [ "Parser", "classuXML_1_1Parser.html", "classuXML_1_1Parser" ],
      [ "ParserException", "classuXML_1_1ParserException.html", "classuXML_1_1ParserException" ]
    ] ]
];